name: Update Submodule in maw.sh

on: [push]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'leetcode-github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Clone the target repository
        run: |
          rm -rf maw.sh
          git clone https://github.com/22mahmoud/maw.sh.git

      - name: Update the submodule
        run: |
          cd maw.sh
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodule"
          
      - name: Push changes
        env:
          REPO_URL: https://22mahmoud:${{ secrets.GH_TOKEN }}@github.com/22mahmoud/maw.sh.git
        run: |
          cd maw.sh
          git push $REPO_URL master
